#pragma once

#include <algorithm>
#include <chrono>
#include <format>
#include <memory>
#include <string>
#include <utility>
#include <vector>
#include <thread>
#include <set>
#include <mutex>
#include <sstream>
#include "../../helpers/imgui_include.hpp"
#include "../../helpers/texture_utils.hpp"
#include "../../external/IconsMaterialDesign.h"

#include "../interface/card.hpp"
#include "rss.hpp"
#include "../../hosts/rss_host.hpp"
#include "../../helpers/image_cache.hpp"
#include "../../helpers/string_helper.hpp"
#include "../../helpers/media_player.hpp"
#include "../../helpers/debug.hpp"
#include "../../helpers/platform_utils.hpp"
#include "../../models/rss/rss_date_parser.hpp"
#include "../../helpers/llm_config.hpp"
#include "../../helpers/fetch.hpp"

namespace rouen::cards
{
    class rss_smart_list : public card
    {
    public:
        rss_smart_list(const std::string &title_str)
        {
            colors[0] = {0.8f, 0.4f, 0.3f, 1.0f}; // Coral/warm primary
            colors[1] = {0.9f, 0.5f, 0.4f, 0.7f};
            get_color(2, ImVec4(1.0f, 0.7f, 0.6f, 1.0f));
            get_color(3, ImVec4(0.85f, 0.85f, 0.85f, 1.0f));
            get_color(4, ImVec4(0.6f, 0.9f, 0.6f, 1.0f));

            smart_list_title = title_str;
            name(std::format("{} - Smart List", smart_list_title));

            rss_host = rss::getHost();
            auto db_path = rouen::platform::get_user_data_path("rss_images.db").string();
            auto cache_dir = rouen::platform::get_user_data_path("cache/rss_images").string();
            image_cache = std::make_shared<::helpers::ImageCache>(db_path, cache_dir, 30);

            loadSmartList();
            width *= 1.5f;
        }

        ~rss_smart_list() override {
            if (active_speak_link == current_speaking_link && !active_speak_link.empty()) {
                rouen::platform::stop_speech();
            }
        }

        void loadSmartList()
        {
            if (!rss_host)
                return;

            auto lists = rss_host->getSmartLists();
            auto it = std::find_if(lists.begin(), lists.end(), [this](const auto& sl) {
                return sl.title == smart_list_title;
            });

            if (it != lists.end()) {
                filter = it->filter;
            } else {
                filter.op = "AND";
                filter.conditions.clear();
                rss_host->saveSmartList(smart_list_title, filter);
            }

            items_limit = 20;
            items_loaded_ = false;

            std::jthread([this, filter_copy = filter]() {
                try {
                    auto loaded_items = rss_host->getFilteredItems(filter_copy);
                    std::lock_guard<std::mutex> lock(items_mutex_);
                    pending_items_ = std::move(loaded_items);
                    items_loaded_ = true;
                } catch (...) {}
            }).detach();
        }

        bool render() override
        {
            if (should_close) {
                return false;
            }
            try
            {
                return render_window([this]()
                {
                    try {
                        renderContent();
                    }
                    catch (const std::exception& e) {
                        RSS_ERROR_FMT("Exception in RSS smart list rendering content: {}", e.what());
                    }
                });
            }
            catch (const std::exception &e)
            {
                RSS_ERROR_FMT("Exception in RSS smart list card: {}", e.what());
                return false;
            }
        }

        std::string get_uri() const override
        {
            return std::format("rss-smart-list:{}", smart_list_title);
        }

        void renderContent()
        {
            if (!rss_host) {
                ImGui::Text("RSS Host is not available.");
                return;
            }

            // Sync pending items to main thread items safely
            {
                std::lock_guard<std::mutex> lock(items_mutex_);
                if (items_loaded_ && !pending_items_.empty()) {
                    items_ = std::move(pending_items_);
                    pending_items_.clear();
                }
            }

            // Sync pending title generated by AI safely
            {
                std::lock_guard<std::mutex> lock(title_mutex_);
                if (!pending_generated_title_.empty()) {
                    new_title_buffer = pending_generated_title_;
                    pending_generated_title_.clear();
                }
            }

            // Option 1 evaluation trigger on window focus transition
            bool is_focused = ImGui::IsWindowFocused(ImGuiFocusedFlags_ChildWindows);
            if (is_focused && !was_focused && !is_editing) {
                loadSmartList();
            }
            was_focused = is_focused;

            if (is_editing) {
                renderFilterBuilder();
                return;
            }

            // Normal Rendering Mode
            ImGui::BeginGroup();
            ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 120.0f);
            ImGui::InputTextWithHint("##search", "Search list...", search_buffer, sizeof(search_buffer));
            
            ImGui::SameLine();
            if (ImGui::SmallButton("×")) {
                search_buffer[0] = '\0';
                items_limit = 20;
            }
            
            ImGui::SameLine();
            ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(colors[0].x, colors[0].y, colors[0].z, 0.7f));
            ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(colors[0].x, colors[0].y, colors[0].z, 0.9f));
            ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(colors[0].x, colors[0].y, colors[0].z, 1.0f));
            if (ImGui::Button(ICON_MD_REFRESH)) {
                loadSmartList();
            }
            if (ImGui::IsItemHovered()) {
                ImGui::SetTooltip("Refresh smart list query");
            }
            ImGui::PopStyleColor(3);

            ImGui::SameLine();
            ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(0.0f, 0.0f, 0.0f, 0.0f));
            ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(colors[0].x, colors[0].y, colors[0].z, 0.3f));
            ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(colors[0].x, colors[0].y, colors[0].z, 0.5f));
            if (ImGui::Button(ICON_MD_SETTINGS)) {
                is_editing = true;
                new_title_buffer = smart_list_title;
            }
            if (ImGui::IsItemHovered()) {
                ImGui::SetTooltip("Edit smart list filters");
            }
            ImGui::PopStyleColor(3);

            ImGui::EndGroup();
            ImGui::Spacing();
            ImGui::Separator();
            ImGui::Spacing();

            // Filter items locally based on search buffer
            std::vector<hosts::RSSHost::FeedItem> displayed_items;
            std::string search_query = search_buffer;
            std::transform(search_query.begin(), search_query.end(), search_query.begin(), ::tolower);

            for (const auto& item : items_) {
                if (search_query.empty()) {
                    displayed_items.push_back(item);
                } else {
                    std::string title = item.title;
                    std::string desc = item.description;
                    std::transform(title.begin(), title.end(), title.begin(), ::tolower);
                    std::transform(desc.begin(), desc.end(), desc.begin(), ::tolower);

                    if (title.find(search_query) != std::string::npos || desc.find(search_query) != std::string::npos) {
                        displayed_items.push_back(item);
                    }
                }
            }

            if (displayed_items.empty()) {
                ImGui::Text("No items found matching the smart list criteria.");
                return;
            }

            // Draw feed list items
            float const dpi_scale = ImGui::GetIO().DisplayFramebufferScale.x;
            ImGui::BeginChild("##smart_items_scroll", ImVec2(0.0f, 0.0f), false, ImGuiWindowFlags_AlwaysVerticalScrollbar);
            
            size_t const count = std::min(displayed_items.size(), static_cast<size_t>(items_limit));
            for (size_t i = 0; i < count; ++i) {
                auto& item = displayed_items[i];
                ImGui::PushID(static_cast<int>(i));

                // Left margin / colored vertical line for visual hierarchy
                ImVec2 p_start = ImGui::GetCursorScreenPos();
                
                ImGui::BeginGroup();
                ImGui::Spacing();
                
                // Item details
                ImGui::Indent(12.0f);
                ImGui::PushTextWrapPos(ImGui::GetContentRegionAvail().x - 16.0f);
                ImGui::TextColored(colors[2], "%s", item.title.c_str());
                ImGui::PopTextWrapPos();

                // Publish Date, duration, and Feed origin
                std::string meta_line;
                if (!item.feed_title.empty()) {
                    meta_line += std::format("[{}] ", item.feed_title);
                }
                
                auto days_ago = std::chrono::duration_cast<std::chrono::days>(std::chrono::system_clock::now() - item.publish_date).count();
                if (days_ago == 0) {
                    meta_line += "Today";
                } else if (days_ago == 1) {
                    meta_line += "Yesterday";
                } else {
                    meta_line += std::format("{} days ago", days_ago);
                }

                if (item.media_duration_seconds.has_value() && item.media_duration_seconds.value() > 0.0) {
                    int total_s = static_cast<int>(item.media_duration_seconds.value());
                    int m = total_s / 60;
                    int s = total_s % 60;
                    meta_line += std::format(" | Duration: {}:{:02d}", m, s);
                }

                ImGui::TextDisabled("%s", meta_line.c_str());

                // Description excerpt
                std::string clean_desc = clean_html(item.description);
                if (clean_desc.length() > 200) {
                    clean_desc = clean_desc.substr(0, 197) + "...";
                }
                ImGui::PushTextWrapPos(ImGui::GetContentRegionAvail().x - 16.0f);
                ImGui::TextColored(colors[3], "%s", clean_desc.c_str());
                ImGui::PopTextWrapPos();

                // Buttons row (Playback, TTS, Link)
                ImGui::Spacing();
                
                // 1. Play button if enclosure or video link is found
                if (item.has_media()) {
                    std::string best_media_url = item.get_best_media_url();
                    if (!best_media_url.empty()) {
                        std::string media_title = "Play Media";
                        if (best_media_url.find("youtube.com") != std::string::npos || best_media_url.find("youtu.be") != std::string::npos) {
                            media_title = "Play YouTube";
                        } else if (best_media_url.find(".mp4") != std::string::npos || best_media_url.find(".MP4") != std::string::npos) {
                            media_title = "Play Video";
                        }
                        media_player::player(best_media_url, colors[0], media_title, item.feed_id, item.link, item.title, item.watermark);
                        ImGui::SameLine();
                    }
                }

                // 2. TTS button
                bool is_currently_speaking_this = (active_speak_link == item.link && !item.link.empty());
                std::string tts_label = is_currently_speaking_this ? (ICON_MD_VOLUME_OFF " Mute") : (ICON_MD_VOLUME_UP " Speak");
                if (ImGui::Button(tts_label.c_str())) {
                    if (is_currently_speaking_this) {
                        rouen::platform::stop_speech();
                        active_speak_link.clear();
                        current_speaking_link.clear();
                    } else {
                        rouen::platform::stop_speech();
                        std::string speech_text = item.title + ". " + clean_html(item.description);
                        auto lang_voice = detect_language_and_select_voice(speech_text, item.link);
                        
                        active_speak_link = item.link;
                        current_speaking_link = item.link;
                        
                        rouen::platform::speak_text_async(speech_text, lang_voice.second, lang_voice.first, [item_link = item.link]() {
                            if (current_speaking_link == item_link) {
                                current_speaking_link.clear();
                            }
                        });
                    }
                }
                ImGui::SameLine();

                // 3. Link opening button
                if (ImGui::Button(ICON_MD_OPEN_IN_NEW " Open Link")) {
                    std::string item_uri = std::format("rss-item:{}|||{}|||{}", item.feed_id, item.link, item.title);
                    "create_card"_sfn(item_uri);
                }

                ImGui::Unindent(12.0f);
                ImGui::EndGroup();

                // Draw vertical side line
                ImVec2 p_end = ImGui::GetCursorScreenPos();
                ImGui::GetWindowDrawList()->AddLine(
                    ImVec2(p_start.x + 4.0f * dpi_scale, p_start.y + 4.0f * dpi_scale),
                    ImVec2(p_start.x + 4.0f * dpi_scale, p_end.y - 4.0f * dpi_scale),
                    ImGui::GetColorU32(colors[0]),
                    2.0f * dpi_scale
                );

                ImGui::Spacing();
                ImGui::Separator();
                ImGui::Spacing();

                ImGui::PopID();
            }

            // Lazy scroll page expansion
            if (ImGui::GetScrollY() >= ImGui::GetScrollMaxY() - 50.0f && count < displayed_items.size()) {
                items_limit += 20;
            }

            ImGui::EndChild();
        }

        void renderFilterBuilder()
        {
            ImGui::TextColored(colors[2], "Edit Smart List: %s", smart_list_title.c_str());
            ImGui::Separator();
            ImGui::Spacing();

            // Smart List Title Editor
            ImGui::TextColored(colors[2], "Title:");
            ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 130.0f);
            char title_buf[256];
            strncpy(title_buf, new_title_buffer.c_str(), sizeof(title_buf));
            title_buf[sizeof(title_buf) - 1] = '\0';
            if (ImGui::InputText("##smart_list_title_editor", title_buf, sizeof(title_buf))) {
                new_title_buffer = title_buf;
            }
            ImGui::SameLine();
            if (ai_title_in_progress_) {
                ImGui::Text("Generating...");
            } else {
                if (ImGui::Button(ICON_MD_AUTO_AWESOME " AI Title")) {
                    generateTitleWithAI();
                }
            }
            if (!ai_title_error_.empty()) {
                ImGui::TextColored(ImVec4(1.0f, 0.4f, 0.4f, 1.0f), "AI Error: %s", ai_title_error_.c_str());
            }
            ImGui::Spacing();
            ImGui::Separator();
            ImGui::Spacing();

            // Match conditions: Match ALL (AND) / Match ANY (OR)
            const char* logical_ops[] = { "AND", "OR" };
            int op_idx = (filter.op == "OR") ? 1 : 0;
            ImGui::SetNextItemWidth(120.0f);
            if (ImGui::Combo("Match Operator", &op_idx, logical_ops, 2)) {
                filter.op = logical_ops[op_idx];
            }
            ImGui::Spacing();
            ImGui::Separator();
            ImGui::Spacing();

            std::vector<int> rows_to_remove;
            for (size_t i = 0; i < filter.conditions.size(); ++i) {
                auto& cond = filter.conditions[i];
                ImGui::PushID(static_cast<int>(i));

                // 1. Field
                const char* fields[] = { "Title", "Summary / Description", "Published Date", "Media Duration", "Tags" };
                const char* field_values[] = { "title", "description", "pub_date", "media_duration_seconds", "feed_tag" };
                int field_idx = 0;
                for (int f = 0; f < 5; ++f) {
                    if (cond.field == field_values[f]) {
                        field_idx = f;
                        break;
                    }
                }
                ImGui::SetNextItemWidth(130.0f);
                if (ImGui::Combo("##field", &field_idx, fields, 5)) {
                    cond.field = field_values[field_idx];
                    if (cond.field == "pub_date" || cond.field == "media_duration_seconds") {
                        cond.op = ">=";
                        cond.value = "";
                    } else if (cond.field == "feed_tag") {
                        cond.op = "IN";
                        cond.value = "";
                    } else {
                        cond.op = "CONTAINS";
                        cond.value = "";
                    }
                }
                ImGui::SameLine();

                // 2. Operator
                std::vector<std::pair<std::string, std::string>> ops;
                if (cond.field == "pub_date" || cond.field == "media_duration_seconds") {
                    ops = { {">", ">"}, {"<", "<"}, {">=", ">="}, {"<=", "<="}, {"==", "=="}, {"!=", "!="} };
                } else if (cond.field == "feed_tag") {
                    ops = { {"IN", "IN"}, {"NOT IN", "NOT IN"} };
                } else {
                    ops = { {"CONTAINS", "CONTAINS"}, {"EXCLUDES", "EXCLUDES"}, {"MATCHES", "MATCHES"}, {"==", "=="}, {"!=", "!="} };
                }

                int op_item_idx = 0;
                std::vector<const char*> op_labels;
                for (size_t o = 0; o < ops.size(); ++o) {
                    op_labels.push_back(ops[o].first.c_str());
                    if (cond.op == ops[o].second) {
                        op_item_idx = static_cast<int>(o);
                    }
                }
                ImGui::SetNextItemWidth(90.0f);
                if (ImGui::Combo("##operator", &op_item_idx, op_labels.data(), static_cast<int>(op_labels.size()))) {
                    cond.op = ops[static_cast<size_t>(op_item_idx)].second;
                }
                ImGui::SameLine();

                // 3. Value Input
                char val_buf[256];
                strncpy(val_buf, cond.value.c_str(), sizeof(val_buf));
                val_buf[sizeof(val_buf) - 1] = '\0';
                
                ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 50.0f);
                
                if (cond.field == "pub_date") {
                    if (ImGui::InputTextWithHint("##value", "Today, Last 24h, Last 7 Days, Last 30 Days", val_buf, sizeof(val_buf))) {
                        cond.value = val_buf;
                    }
                } else if (cond.field == "media_duration_seconds") {
                    if (ImGui::InputTextWithHint("##value", "Seconds (e.g. 300, 1800)", val_buf, sizeof(val_buf))) {
                        cond.value = val_buf;
                    }
                } else if (cond.field == "feed_tag") {
                    if (ImGui::InputTextWithHint("##value", "e.g. News, Podcasts, Comedy", val_buf, sizeof(val_buf))) {
                        cond.value = val_buf;
                    }
                } else {
                    if (ImGui::InputText("##value", val_buf, sizeof(val_buf))) {
                        cond.value = val_buf;
                    }
                }
                ImGui::SameLine();

                // 4. Remove
                if (ImGui::Button(ICON_MD_DELETE)) {
                    rows_to_remove.push_back(static_cast<int>(i));
                }

                ImGui::PopID();
            }

            for (auto r : rows_to_remove) {
                filter.conditions.erase(filter.conditions.begin() + r);
            }

            ImGui::Spacing();
            if (ImGui::Button(ICON_MD_ADD " Add Condition")) {
                filter.conditions.push_back({ "title", "CONTAINS", "" });
            }

            ImGui::Spacing();
            ImGui::Separator();
            ImGui::Spacing();

            if (ImGui::Button(ICON_MD_SAVE " Save Filters")) {
                if (new_title_buffer != smart_list_title && !new_title_buffer.empty()) {
                    rss_host->deleteSmartList(smart_list_title);
                    smart_list_title = new_title_buffer;
                    name(std::format("{} - Smart List", smart_list_title));
                }
                rss_host->saveSmartList(smart_list_title, filter);
                is_editing = false;
                loadSmartList();
            }
            ImGui::SameLine();
            if (ImGui::Button("Cancel")) {
                is_editing = false;
                loadSmartList();
            }
            ImGui::SameLine();

            ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(0.7f, 0.15f, 0.15f, 0.8f));
            ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(0.85f, 0.2f, 0.2f, 0.9f));
            ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(0.6f, 0.1f, 0.1f, 1.0f));
            if (ImGui::Button(ICON_MD_DELETE " Delete Smart List")) {
                ImGui::OpenPopup("Delete Smart List?");
            }
            ImGui::PopStyleColor(3);

            if (ImGui::BeginPopupModal("Delete Smart List?", NULL, ImGuiWindowFlags_AlwaysAutoResize)) {
                ImGui::Text("Are you sure you want to delete this smart list?\nThis action cannot be undone.\n\n");
                ImGui::Separator();
                
                if (ImGui::Button("Yes, Delete", ImVec2(120, 0))) {
                    rss_host->deleteSmartList(smart_list_title);
                    should_close = true;
                    ImGui::CloseCurrentPopup();
                }
                ImGui::SetItemDefaultFocus();
                ImGui::SameLine();
                if (ImGui::Button("Cancel", ImVec2(120, 0))) {
                    ImGui::CloseCurrentPopup();
                }
                ImGui::EndPopup();
            }
        }

    public:
        void set_renderer(SDL_Renderer *r)
        {
            renderer = r;
        }

    private:
        std::string smart_list_title;
        media::rss::filter_group filter;
        std::vector<hosts::RSSHost::FeedItem> items_;
        std::vector<hosts::RSSHost::FeedItem> pending_items_;
        std::mutex items_mutex_;
        bool items_loaded_ = false;
        bool was_focused = false;
        int items_limit = 20;
        bool is_editing = false;
        bool should_close = false;
        char search_buffer[256] = "";

        std::shared_ptr<hosts::RSSHost> rss_host;
        std::shared_ptr<::helpers::ImageCache> image_cache;
        SDL_Renderer *renderer = nullptr;

        std::string new_title_buffer;
        std::string pending_generated_title_;
        std::mutex title_mutex_;
        bool ai_title_in_progress_ = false;
        std::string ai_title_error_;

        void generateTitleWithAI() {
            if (ai_title_in_progress_) return;

            if (!helpers::LLMConfig::is_configured()) {
                ai_title_error_ = "LLM not configured";
                return;
            }

            ai_title_in_progress_ = true;
            ai_title_error_.clear();

            std::jthread([this]() {
                try {
                    auto llm_instance = helpers::LLMConfig::create_llm_instance();
                    if (!llm_instance) {
                        ai_title_error_ = "Failed to create LLM";
                        ai_title_in_progress_ = false;
                        return;
                    }

                    std::string filter_description = std::format("Logical operator: {}\n", filter.op);
                    for (const auto& cond : filter.conditions) {
                        filter_description += std::format("- Field: {}, Operator: {}, Value: {}\n", cond.field, cond.op, cond.value);
                    }

                    std::string prompt = std::format(
                        "I have an RSS smart list with the following filters:\n"
                        "{}\n"
                        "Please generate a short, descriptive, and punchy title for this smart list (e.g., 'Recent Tech Podcasts', 'Short News Articles', 'comedy & entertainment'). "
                        "Return ONLY the title text, nothing else. No quotation marks, no explanations, no prefix.",
                        filter_description
                    );

                    auto settings = helpers::LLMConfig::get_current_config();
                    auto fetcher = std::make_shared<http::fetch>();

                    auto response = llm_instance->sendMessage(
                        prompt,
                        [fetcher](const std::string& url, const std::string& data, auto header_client) {
                            return fetcher->post(url, data, header_client);
                        },
                        "user",
                        settings.model_name,
                        "",
                        0.7f
                    );

                    if (!response.choices.empty() && !response.choices[0].message.content.empty()) {
                        std::string generated = response.choices[0].message.content;
                        generated.erase(0, generated.find_first_not_of(" \t\r\n\"'"));
                        generated.erase(generated.find_last_not_of(" \t\r\n\"'") + 1);
                        if (!generated.empty()) {
                            std::lock_guard<std::mutex> lock(title_mutex_);
                            pending_generated_title_ = generated;
                        }
                    } else {
                        ai_title_error_ = "Empty response from AI";
                    }
                } catch (const std::exception& e) {
                    ai_title_error_ = e.what();
                }
                ai_title_in_progress_ = false;
            }).detach();
        }

        inline static std::string active_speak_link;
        inline static std::string current_speaking_link;

        std::string clean_html(std::string_view html)
        {
            std::string text;
            text.reserve(html.size());
            bool in_tag = false;
            for (char c : html) {
                if (c == '<') in_tag = true;
                else if (c == '>') in_tag = false;
                else if (!in_tag) text.push_back(c);
            }
            return text;
        }

        std::pair<std::string, std::string> detect_language_and_select_voice(std::string_view text, std::string_view url)
        {
            std::string lower_url = std::string(url);
            std::transform(lower_url.begin(), lower_url.end(), lower_url.begin(), ::tolower);
            
            if (lower_url.find(".es") != std::string::npos || 
                lower_url.find("elpais.com") != std::string::npos ||
                lower_url.find("clarin.com") != std::string::npos ||
                lower_url.find("infobae.com") != std::string::npos) {
                return {"es", "Mónica"};
            }
            
            if (lower_url.find(".fr") != std::string::npos) {
                return {"fr", "Flo"};
            }
            
            if (lower_url.find(".de") != std::string::npos) {
                return {"de", "Eddy"};
            }
            
            if (lower_url.find(".it") != std::string::npos) {
                return {"it", "Flo"};
            }
            
            std::string lower_text = std::string(text);
            std::transform(lower_text.begin(), lower_text.end(), lower_text.begin(), ::tolower);
            
            int es_score = 0;
            std::vector<std::string> es_words = {" el ", " la ", " de ", " en ", " y ", " que ", " los ", " las ", " con ", " para "};
            for (const auto& w : es_words) {
                size_t pos = 0;
                while ((pos = lower_text.find(w, pos)) != std::string::npos) {
                    es_score++;
                    pos += w.length();
                }
            }
            
            int en_score = 0;
            std::vector<std::string> en_words = {" the ", " of ", " and ", " to ", " a ", " in ", " is ", " that ", " with ", " for "};
            for (const auto& w : en_words) {
                size_t pos = 0;
                while ((pos = lower_text.find(w, pos)) != std::string::npos) {
                    en_score++;
                    pos += w.length();
                }
            }
            
            if (es_score > en_score && es_score > 2) {
                return {"es", "Mónica"};
            }
            
            return {"", ""};
        }
    };
}
